name: Check Release

on:
  push:
    branches:
    - 'r/[0-9]+.[0-9]+.[0-9]+'
    - 'r/[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+'

jobs:
  check-version:
    name: check-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get the release version from the branch
      if: env.VERSION == ''
      run: |
        VERSION=${{ github.ref_name }}
        VERSION=${VERSION##r/}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Show the version
      run: |
        echo "version is: $VERSION"
    - name: Check that tag version and Cargo.toml version are the same
      shell: bash
      run: |
        if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
          echo "version does not match Cargo.toml" >&2
          exit 1
        fi
    outputs:
      version: ${{ env.VERSION }}

  check-release:
    name: check-release
    needs: ['check-version']
    runs-on: ${{ matrix.os }}
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        build: [linux, macos, windows]
        include:
        - build: linux
          os: ubuntu-latest
        - build: macos
          os: macos-latest
        - build: windows
          os: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build release binary
      shell: bash
      run: |
        cargo build --verbose --release -p waj
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          bin="target/release/waj.exe"
        else
          bin="target/release/waj"
        fi
        echo "BIN=$bin" >> $GITHUB_ENV

    - name: Strip release binary (macos)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: strip "$BIN"

    - name: Determine archive name
      shell: bash
      run: |
        version="${{ needs.create-release.outputs.version }}"
        echo "ARCHIVE=waj-$version-${{ matrix.build }}" >> $GITHUB_ENV

    - name: Creating directory for archive
      shell: bash
      run: |
        mkdir -p "$ARCHIVE"/{complete,doc}
        cp "$BIN" "$ARCHIVE"/
        cp {README.md,LICENSE-MIT} "$ARCHIVE"/
        cp Changelog.md "$ARCHIVE"/doc/

    - name: Generate completions
      shell: bash
      run: |
        "$BIN" --version
        "$BIN" --generate-complete=bash > "$ARCHIVE/complete/waj.bash"
        "$BIN" --generate-complete=fish > "$ARCHIVE/complete/waj.fish"
        "$BIN" --generate-complete=powershell > "$ARCHIVE/complete/_waj.ps1"
        "$BIN" --generate-complete=zsh > "$ARCHIVE/complete/_waj"

    - name: Generate man page
      shell: bash
      run: |
        "$BIN" --generate-man-page > "$ARCHIVE/doc/waj.1"
        commands="create list serve"
        for command in $commands
        do
          "$BIN" --generate-man-page=$command > "$ARCHIVE/doc/waj-$command.1"
        done

    - name: Build archive (Windows)
      shell: bash
      if: matrix.os == 'windows-latest'
      run: |
        7z a "$ARCHIVE.zip" "$ARCHIVE"
        certutil -hashfile "$ARCHIVE.zip" SHA256 > "$ARCHIVE.zip.sha256"
        echo "ASSET=$ARCHIVE.zip" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.zip.sha256" >> $GITHUB_ENV

    - name: Build archive (Unix)
      shell: bash
      if: matrix.os != 'windows-latest'
      run: |
        tar czf "$ARCHIVE.tar.gz" "$ARCHIVE"
        shasum -a 256 "$ARCHIVE.tar.gz" > "$ARCHIVE.tar.gz.sha256"
        echo "ASSET=$ARCHIVE.tar.gz" >> $GITHUB_ENV
        echo "ASSET_SUM=$ARCHIVE.tar.gz.sha256" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pre_release-${{ matrix.build }}-waj
        path: |
          ${{ env.ASSET }}
        compression-level: 0

  check-publication:
    name: Check cargo publication
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish --dry-run --workspace
